name: Salesforce to Shutterstock Transfer

on:
  workflow_dispatch:
    inputs:
      salesforce_record_id:
        description: 'Salesforce Record ID that triggered this'
        required: false
        type: string
  schedule:
    - cron: '0 * * * *'

jobs:
  transfer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Print trigger info
      run: |
        echo "Triggered by Salesforce record: ${{ github.event.inputs.salesforce_record_id }}"
        echo "Event payload: ${{ toJson(github.event) }}"
        
    # Rest of your existing workflow steps...
